---

- name: Check that the sysctl.conf exists
  stat:
    path: /etc/sysctl.conf
  register: sysctl_stat_result

- name: Harden TCP/IP stack against SYN floods
  sysctl: name="net.ipv4.tcp_syncookies" value=1 sysctl_set=yes state=present reload=yes
  when: sysctl_stat_result.stat.exists == True
