---
# tasks file for vps-maintenance

- name: Ensure aptitude is installed
  apt: package=aptitude state=present

- name: Update apt keys
  command: apt-key update

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Run apt upgrade
  apt: upgrade=safe

- name: Install unattended-upgrades
  apt: pkg=unattended-upgrades state=present

- name: Adjust apt update intervals
  copy: src=apt_auto_upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades

- name: Make sure unattended-upgrades only installs security updates
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="-updates" state=absent

- name: Make sure unattended-upgrades only installs security updates
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="-proposed" state=absent

- name: Make sure unattended-upgrades only installs security updates
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="-backports" state=absent
